/**
 * AnaMark .tun (TUN) tuning file writer.
 *
 * Emits the broadly-compatible v1 layout with both a [Tuning] section (integer
 * cents) and an [Exact Tuning] section (5-decimal-place cents).  All cent values
 * are **absolute cents above basefreq** — i.e. 1200·log₂(f / basefreq).
 *
 * File structure:
 *
 * ```
 * ; <name>
 * ; Generated by ruri
 * [Tuning]
 * note 0=<int cents>
 * ...
 * note 127=<int cents>
 * [Exact Tuning]
 * basefreq=8.1757989156437073336
 * note 0=<float cents, toFixed(5)>
 * ...
 * note 127=<float cents, toFixed(5)>
 * ```
 *
 * The default basefreq is 8.1757989156437073336 Hz, which equals MIDI note 0
 * when A4 = 440 Hz (i.e. 440 × 2^(−69/12)).  With this basefreq, 12-TET gives
 * note k = k×100 cents exactly.
 *
 * Convenience usage with an existing TuningSystem:
 *   `writeTun(tuningToMtsFrequencies(t), 'My Scale')`
 */

import { freqToCents } from '../core/cents.js';
import { type Chord, realizeChordFreqs } from '../core/chord.js';
import { freqToMidiFloat, midiToFreq, A4_HZ_DEFAULT } from '../core/midi.js';
import { type TuningSystem, degreeToFreq } from '../core/tuning.js';
import { type Scale, scaleToFreqs, tuningToScale } from '../core/scale.js';
import { type Spectrum } from '../core/spectrum.js';
import { getTuningById } from '../data/presets.js';
import { scaleChordProgressionSmf, scaleToSmf } from './smf.js';
import { type ScalaScale, tuningToScl, writeScl, scaleToSubsetSclText } from './scala.js';
import { bestModeWav, pluckScaleWav } from './wav.js';
import { tuningToMts, scaleToMts } from './mts.js';

/** Default base frequency: MIDI note 0 at A4 = 440 Hz (440 × 2^(−69/12)). */
export const TUN_DEFAULT_BASEFREQ_HZ = 440 * 2 ** (-69 / 12);

/** Options for {@link writeTun}. */
export interface TunOptions {
  /** Base frequency in Hz. Default {@link TUN_DEFAULT_BASEFREQ_HZ}. */
  readonly basefreqHz?: number;
}

/**
 * Write 128 frequencies as an AnaMark .tun file.
 *
 * @param frequenciesHz - Frequencies for MIDI keys 0..127 (must have length 128,
 *   all finite and > 0).
 * @param name - Human-readable tuning name; control characters and newlines are
 *   replaced with spaces to keep the comment line well-formed.
 * @param opts - Optional base frequency override.
 * @throws {RangeError} if frequenciesHz.length !== 128, any frequency is not
 *   finite or ≤ 0, or basefreqHz is not finite or ≤ 0.
 */
export function writeTun(
  frequenciesHz: readonly number[],
  name: string,
  opts?: TunOptions,
): string {
  if (frequenciesHz.length !== 128) {
    throw new RangeError(
      `writeTun: frequenciesHz must have length 128, got ${frequenciesHz.length}`,
    );
  }

  const basefreqHz = opts?.basefreqHz ?? TUN_DEFAULT_BASEFREQ_HZ;

  if (!Number.isFinite(basefreqHz) || basefreqHz <= 0) {
    throw new RangeError(`writeTun: basefreqHz must be finite and > 0, got ${basefreqHz}`);
  }

  // Validate all frequencies up front (fail fast).
  for (let i = 0; i < 128; i++) {
    const hz = frequenciesHz[i] as number;
    if (!Number.isFinite(hz) || hz <= 0) {
      throw new RangeError(`writeTun: frequenciesHz[${i}] must be finite and > 0, got ${hz}`);
    }
  }

  // Strip control characters (including newlines) from the name.
  // eslint-disable-next-line no-control-regex
  const safeName = name.replace(/[\x00-\x1f\x7f]/g, ' ');

  const lines: string[] = [];

  // Comment header.
  lines.push(`; ${safeName}`);
  lines.push('; Generated by ruri');

  // [Tuning] section — integer cents.
  lines.push('[Tuning]');
  for (let k = 0; k < 128; k++) {
    const hz = frequenciesHz[k] as number;
    const c = freqToCents(hz, basefreqHz);
    lines.push(`note ${k}=${Math.round(c)}`);
  }

  // [Exact Tuning] section — 5-decimal-place cents.
  lines.push('[Exact Tuning]');
  // Emit the ACTUAL basefreq used for the cent computations (not the default),
  // so the file is internally consistent and a conforming parser recovers the
  // same pitches. Using the default here for a custom basefreq would shift every
  // note by log2(basefreqHz / default) octaves.
  lines.push(`basefreq=${basefreqHz.toPrecision(20)}`);
  for (let k = 0; k < 128; k++) {
    const hz = frequenciesHz[k] as number;
    const c = freqToCents(hz, basefreqHz);
    lines.push(`note ${k}=${c.toFixed(5)}`);
  }

  return lines.join('\n') + '\n';
}

/** Options for {@link chordToTun}. */
export interface ChordToTunOptions extends TunOptions {
  /**
   * A4 reference frequency in Hz used to fill non-chord MIDI keys with standard 12-TET.
   * Default: 440.
   */
  readonly a4Hz?: number;
}

/**
 * Export a microtonal `Chord` directly as an AnaMark `.tun` string.
 *
 * Socratic Q114: `chordToMts(chord, rootHz)` maps a chord's exact frequencies onto
 * the nearest MIDI keys and returns a ready-to-send SysEx byte-stream — but there is
 * no `.tun` equivalent. Going from a `Chord` to a `.tun` file still requires three
 * manual steps: `realizeChordFreqs → fill 128-key array → writeTun`.
 * If `Chord` is truly first-class (with `chordToMts`, `chordToScl`, `chordToSmf`…),
 * exporting it as `.tun` should also be one call.
 *
 * Algorithm (mirrors `chordToMts`):
 * 1. Realize chord frequencies: `realizeChordFreqs(chord, rootHz)`.
 * 2. Fill a 128-entry array with standard 12-TET frequencies (via `midiToFreq`).
 * 3. For each chord frequency, find the nearest MIDI key (clamped to [0, 127]) and
 *    overwrite that slot with the exact chord Hz.
 * 4. Encode with `writeTun` and return the `.tun` string.
 *
 * Non-chord MIDI keys retain standard 12-TET so that an unrelated synth part is not
 * detuned.
 *
 * @param chord   - The chord to export.
 * @param rootHz  - Absolute frequency of the chord root in Hz.
 * @param name    - Human-readable name for the `.tun` file comment header.
 *                  Defaults to `chord.name` (or `'chord'` if that is empty).
 * @param opts    - Optional A4 reference Hz and basefreq override.
 *
 * @throws {RangeError} if `chord` has no intervals.
 * @throws {RangeError} if `rootHz` is not finite or ≤ 0.
 *
 * @example
 * const justMajor = chordFromRatios('just-major', [[1,1],[5,4],[3,2]]);
 * const tun = chordToTun(justMajor, 261.63);
 * fs.writeFileSync('just-major.tun', tun, 'utf8');
 */
export function chordToTun(
  chord: Chord,
  rootHz: number,
  name?: string,
  opts?: ChordToTunOptions,
): string {
  if (chord.intervals.length === 0) {
    throw new RangeError('chordToTun: chord must have at least one interval');
  }
  if (!Number.isFinite(rootHz) || rootHz <= 0) {
    throw new RangeError(`chordToTun: rootHz must be finite and > 0, got ${rootHz}`);
  }

  const a4Hz = opts?.a4Hz ?? A4_HZ_DEFAULT;
  const tunName = name ?? (chord.name.length > 0 ? chord.name : 'chord');

  // Start with standard 12-TET for all 128 MIDI keys.
  const frequencies: number[] = Array.from({ length: 128 }, (_, k) => midiToFreq(k, a4Hz));

  // Overwrite the nearest MIDI key for each chord frequency.
  const chordFreqs = realizeChordFreqs(chord, rootHz);
  for (const hz of chordFreqs) {
    const midiFloat = freqToMidiFloat(hz, a4Hz);
    const key = Math.max(0, Math.min(127, Math.round(midiFloat)));
    (frequencies as number[])[key] = hz;
  }

  const { a4Hz: _a4Hz, ...tunOpts } = opts ?? {};
  void _a4Hz;
  return writeTun(frequencies, tunName, Object.keys(tunOpts).length > 0 ? tunOpts : undefined);
}

/** Options for {@link scaleToTunText}. */
export interface ScaleToTunOptions extends TunOptions {
  /**
   * MIDI note number for the first scale degree.
   * The scale frequencies are written into slots `middleNote..middleNote+n-1`.
   * Default: 60 (middle C).
   */
  readonly middleNote?: number;
  /**
   * A4 reference frequency in Hz used to fill non-scale MIDI keys with standard 12-TET.
   * Default: 440.
   */
  readonly a4Hz?: number;
}

/**
 * Export a `Scale` as an AnaMark `.tun` text file in one call.
 *
 * Socratic Q129: `scaleToMts(scale, tuning)` exports a `Scale` as MIDI Tuning
 * Standard SysEx — but there is no `.tun` equivalent. Going from a `Scale` to a
 * `.tun` string requires: `scaleToFreqs → fill 128-key array → writeTun`, three
 * explicit steps. If `Scale` is truly first-class across output formats (as shown
 * by `scaleToMts`, `scaleToScl`, etc.), exporting it as `.tun` should also be
 * one call.
 *
 * Algorithm:
 * 1. `scaleToFreqs(scale, tuning)` — absolute Hz for each scale degree.
 * 2. Fill a 128-entry array with standard 12-TET frequencies (via `midiToFreq`).
 * 3. Overwrite slots `middleNote..middleNote+n-1` with the scale's Hz values.
 * 4. Encode with `writeTun(frequencies, name ?? scale.id, opts)`.
 *
 * Non-scale MIDI keys retain standard 12-TET so that an unrelated synth part is
 * not detuned.
 *
 * @param scale  - The scale to export.
 * @param tuning - The parent `TuningSystem` the scale belongs to.
 * @param name   - Human-readable name for the `.tun` file comment header.
 *                 Defaults to `scale.id`.
 * @param opts   - Optional middle-note anchor, A4 Hz, and basefreq override.
 *
 * @throws {RangeError} if `scale` is incompatible with `tuning`.
 * @throws {RangeError} if `scale` has no degrees.
 *
 * @example
 * const major = { id: 'major', name: 'Ionian', tuningId: '12-tet', degreeIndices: [0,2,4,5,7,9,11] };
 * const tun = scaleToTunText(major, equalTemperament12(440));
 * fs.writeFileSync('major.tun', tun, 'utf8');
 */
export function scaleToTunText(
  scale: Scale,
  tuning: TuningSystem,
  name?: string,
  opts?: ScaleToTunOptions,
): string {
  const middleNote = opts?.middleNote ?? 60;
  const a4Hz = opts?.a4Hz ?? A4_HZ_DEFAULT;
  const tunName = name ?? scale.id;

  // Start with standard 12-TET for all 128 MIDI keys.
  const frequencies: number[] = Array.from({ length: 128 }, (_, k) => midiToFreq(k, a4Hz));

  // Overwrite scale degree slots with the scale's exact frequencies.
  const scaleFreqs = scaleToFreqs(scale, tuning);
  for (let i = 0; i < scaleFreqs.length; i++) {
    const key = middleNote + i;
    if (key >= 0 && key < 128) {
      (frequencies as number[])[key] = scaleFreqs[i] as number;
    }
  }

  const { middleNote: _mn, a4Hz: _a4Hz, ...tunOpts } = opts ?? {};
  void _mn;
  void _a4Hz;
  return writeTun(frequencies, tunName, Object.keys(tunOpts).length > 0 ? tunOpts : undefined);
}

/** Options for {@link tuningToTun}. */
export interface TuningToTunOptions extends TunOptions {
  /** MIDI key number that maps to `tuning.referenceHz`. Default 69 (A4). */
  readonly anchorMidiNote?: number;
}

/**
 * Export a `TuningSystem` directly as an AnaMark `.tun` string in one call.
 *
 * Socratic Q151 (prerequisite): `tuningToMts` exports a `TuningSystem` as MTS SysEx
 * in one call — but there is no `.tun` equivalent. Going from a tuning to a `.tun`
 * string requires: `tuningToMtsFrequencies` → `writeTun` — two steps. If a tuning is
 * truly first-class across output formats, exporting it as `.tun` should also be one call.
 *
 * Maps all 128 MIDI keys to frequencies via `degreeToFreq(tuning, k - anchorMidiNote)`,
 * then encodes with `writeTun`. Key `anchorMidiNote` (default 69, A4) produces
 * `tuning.referenceHz`.
 *
 * @param tuning - The tuning system to export.
 * @param name   - Optional name for the `.tun` comment header. Defaults to `tuning.id`.
 * @param opts   - Optional anchor MIDI note and basefreq override.
 * @returns A `.tun` text string ready to write to a file.
 *
 * @example
 * const tun = tuningToTun(edo(19));
 * fs.writeFileSync('19edo.tun', tun);
 */
export function tuningToTun(
  tuning: TuningSystem,
  name?: string,
  opts?: TuningToTunOptions,
): string {
  const anchorMidiNote = opts?.anchorMidiNote ?? 69;
  const { anchorMidiNote: _anchor, ...tunOpts } = opts ?? {};
  void _anchor;
  const frequencies = Array.from({ length: 128 }, (_, k) =>
    degreeToFreq(tuning, k - anchorMidiNote),
  );
  return writeTun(
    frequencies,
    name ?? tuning.id,
    Object.keys(tunOpts).length > 0 ? tunOpts : undefined,
  );
}

/**
 * Export a tuning preset as a `.tun` string in one call.
 *
 * Socratic Q151: "If we can build a chord progression from a preset, the same progression
 * converted to TUN format should be one call — can it?" `getTuningById(presetId)` →
 * `tuningToTun(tuning, name, opts)` exports the tuning itself as TUN. The `pattern` and
 * `rootHz` parameters are accepted for API consistency but the TUN export covers the full
 * tuning (not just the progression notes).
 *
 * Returns `undefined` if the preset id is not found.
 *
 * @param presetId - Id string of a curated tuning preset.
 * @param pattern  - Degree-offset pattern (accepted for API consistency; not used in TUN export).
 * @param rootHz   - Root frequency in Hz (accepted for API consistency; not used in TUN export).
 * @param opts     - Optional TUN encoding options forwarded to `tuningToTun`.
 * @param presets  - Optional preset pool (defaults to `ALL_PRESETS`).
 * @returns A `.tun` text string, or `undefined` if preset not found.
 *
 * @example
 * const tun = presetProgressionTun('just-5-limit', [0, 3, 4, 0], 261.63);
 * if (tun) fs.writeFileSync('just5.tun', tun);
 */
export function presetProgressionTun(
  presetId: string,
  pattern: readonly number[],
  rootHz: number,
  opts?: TuningToTunOptions,
): string | undefined {
  void pattern; // accepted for API consistency; TUN covers the full tuning
  void rootHz; // accepted for API consistency
  const tuning = getTuningById(presetId);
  if (tuning === undefined) return undefined;
  return tuningToTun(tuning, undefined, opts);
}

/**
 * Export a scale's chord progression as both SMF (MIDI) and TUN simultaneously.
 *
 * Socratic Q154: "If we can export a scale progression to SMF, exporting the same
 * progression as both SMF and TUN simultaneously should be one call — can it?"
 * `scaleChordProgressionSmf(scale, tuning, rootHz)` exports to MIDI;
 * `scaleToTunText(scale, tuning, name)` exports to TUN — but both together requires
 * two separate calls. If these exports are first-class, bundling them should be one call.
 *
 * @param scale   - The parent scale whose diatonic chords to export.
 * @param tuning  - The parent `TuningSystem`.
 * @param rootHz  - Root frequency for the SMF MIDI pitch mapping.
 * @param name    - Optional name for the `.tun` file header. Defaults to `scale.id`.
 * @returns `{ smf: Uint8Array, tun: string }` — SMF bytes and TUN text.
 *
 * @throws {RangeError} if `scale` is incompatible with `tuning`.
 * @throws {RangeError} if the scale has no degrees.
 *
 * @example
 * const { smf, tun } = scaleProgressionBundle(major, t12, 261.63, 'major');
 * fs.writeFileSync('major.mid', smf);
 * fs.writeFileSync('major.tun', tun);
 */
export function scaleProgressionBundle(
  scale: Scale,
  tuning: TuningSystem,
  rootHz: number,
  name?: string,
): { smf: Uint8Array; tun: string } {
  const smf = scaleChordProgressionSmf(scale, tuning, rootHz);
  const tun = scaleToTunText(scale, tuning, name);
  return { smf, tun };
}

/**
 * Export a `TuningSystem` as SMF (sequential scale notes), TUN, and Scala `.scl` simultaneously.
 *
 * Socratic Q174: "If we can export a scale as SMF and as TUN simultaneously, the same should
 * work for a TUNING SYSTEM (not just a Scale) — can it?" `scaleProgressionBundle` does both for
 * a `Scale`; doing the same for a raw `TuningSystem` still requires `tuningToScl` → `tuningToTun`
 * → `tuningToScale` → `scaleToSmf` — four explicit steps. If a tuning is truly first-class, a
 * three-format export bundle should be one call.
 *
 * Algorithm:
 * 1. `tuningToScl(tuning)` → `ScalaScale`.
 * 2. `tuningToTun(tuning, name, opts)` → TUN string.
 * 3. `tuningToScale(tuning)` → full `Scale`; `scaleToSmf(scale, tuning, tuning.referenceHz)` → SMF.
 *
 * @param tuning - The tuning system to export.
 * @param opts   - Optional TUN encoding options (anchor MIDI note, basefreq).
 * @returns `{ smf: Uint8Array, tun: string, scl: ScalaScale }`.
 *
 * @throws {RangeError} if tuning has no degrees.
 *
 * @example
 * const { smf, tun, scl } = tuningBundle(edo(19));
 * fs.writeFileSync('19edo.mid', smf);
 * fs.writeFileSync('19edo.tun', tun);
 * fs.writeFileSync('19edo.scl', writeScl(scl));
 */
export function tuningBundle(
  tuning: TuningSystem,
  opts?: TuningToTunOptions,
): { smf: Uint8Array; tun: string; scl: ScalaScale } {
  const scl = tuningToScl(tuning);
  const tun = tuningToTun(tuning, undefined, opts);
  const scale = tuningToScale(tuning);
  const smf = scaleToSmf(scale, tuning, tuning.referenceHz);
  return { smf, tun, scl };
}

/**
 * Export a `TuningSystem` as WAV + SMF + SCL text + TUN + MTS in one call.
 *
 * Socratic Q240: "If a TuningSystem is truly first-class, exporting it as
 * WAV + SMF + SCL + TUN + MTS should be one call — can it?"
 * `tuningBundle` already bundles SMF + TUN + SCL but has no WAV or MTS.
 * If a tuning is truly first-class across all output formats, a five-format
 * export bundle should be one call.
 *
 * Algorithm:
 * 1. `tuningBundle(tuning, opts)` → `{ smf, tun, scl: ScalaScale }`.
 * 2. `writeScl(scl)` → `.scl` text string.
 * 3. `bestModeWav(tuning, rootHz ?? tuning.referenceHz, spectrum)` → WAV bytes.
 * 4. `tuningToMts(tuning)` → MTS SysEx bytes.
 *
 * @param tuning   - The tuning system to export.
 * @param rootHz   - Root frequency in Hz for WAV rendering. Defaults to `tuning.referenceHz`.
 * @param spectrum - Optional instrument spectrum for WAV synthesis.
 * @param opts     - Optional TUN encoding options (name, anchor MIDI note, basefreq).
 * @returns `{ wav, smf, scl, tun, mts }` — all five formats simultaneously.
 *
 * @throws {RangeError} if tuning has no degrees.
 *
 * @example
 * const { wav, smf, scl, tun, mts } = tuningToFullBundle(edo(19));
 * fs.writeFileSync('19edo.wav', wav);
 * fs.writeFileSync('19edo.mid', smf);
 * fs.writeFileSync('19edo.scl', scl);
 * fs.writeFileSync('19edo.tun', tun);
 * port.send(mts);
 */
export function tuningToFullBundle(
  tuning: TuningSystem,
  rootHz?: number,
  spectrum?: Spectrum,
  opts?: { name?: string },
): { wav: Uint8Array; smf: Uint8Array; scl: string; tun: string; mts: Uint8Array } {
  const tunOpts: TuningToTunOptions | undefined =
    opts?.name !== undefined ? { anchorMidiNote: 69 } : undefined;
  const { smf, tun, scl: sclObj } = tuningBundle(tuning, tunOpts);
  const scl = writeScl(sclObj);
  const effectiveRootHz = rootHz ?? tuning.referenceHz;
  const wav = bestModeWav(tuning, effectiveRootHz, spectrum);
  const mts = tuningToMts(tuning, opts?.name);
  return { wav, smf, scl, tun, mts };
}

/**
 * Export a `Scale` as WAV + SMF + SCL text + TUN + MTS in one call.
 *
 * Socratic Q247: "If a Scale is truly first-class — exporting it as WAV + SMF + SCL + TUN + MTS
 * should be one call — can it?" → No → implement.
 *
 * Algorithm:
 * 1. `scaleToSmf(scale, tuning, rootHz ?? tuning.referenceHz)` → SMF bytes.
 * 2. `tuningToTun(tuning, name)` → TUN text.
 * 3. `scaleToSubsetSclText(scale, tuning, name)` → SCL text.
 * 4. `pluckScaleWav(scale, tuning)` → WAV bytes.
 * 5. `scaleToMts(scale, tuning)` → MTS SysEx bytes.
 *
 * @param scale    - The scale to export.
 * @param tuning   - The parent `TuningSystem`.
 * @param rootHz   - Root frequency in Hz for SMF pitch mapping. Defaults to `tuning.referenceHz`.
 * @param spectrum - Unused (accepted for API forward-compatibility).
 * @param name     - Optional name for SCL/TUN headers.
 * @returns `{ wav, smf, scl, tun, mts }` — all five formats simultaneously.
 *
 * @throws {RangeError} if `scale` is incompatible with `tuning`.
 * @throws {RangeError} if the scale has no degrees.
 *
 * @example
 * const t12 = equalTemperament12(440);
 * const major: Scale = { id: 'major', name: 'Ionian', tuningId: '12-tet', degreeIndices: [0,2,4,5,7,9,11] };
 * const { wav, smf, scl, tun, mts } = scaleFullBundle(major, t12);
 */
export function scaleFullBundle(
  scale: Scale,
  tuning: TuningSystem,
  rootHz?: number,
  spectrum?: Spectrum,
  name?: string,
): { wav: Uint8Array; smf: Uint8Array; scl: string; tun: string; mts: Uint8Array } {
  void spectrum; // accepted for API forward-compatibility
  const effectiveRootHz = rootHz ?? tuning.referenceHz;
  const smf = scaleToSmf(scale, tuning, effectiveRootHz);
  const tun = tuningToTun(tuning, name);
  const scl = scaleToSubsetSclText(scale, tuning, name);
  const wav = pluckScaleWav(scale, tuning);
  const mts = scaleToMts(scale, tuning, name);
  return { wav, smf, scl, tun, mts };
}
