/**
 * AnaMark .tun (TUN) tuning file writer.
 *
 * Emits the broadly-compatible v1 layout with both a [Tuning] section (integer
 * cents) and an [Exact Tuning] section (5-decimal-place cents).  All cent values
 * are **absolute cents above basefreq** — i.e. 1200·log₂(f / basefreq).
 *
 * File structure:
 *
 * ```
 * ; <name>
 * ; Generated by ruri
 * [Tuning]
 * note 0=<int cents>
 * ...
 * note 127=<int cents>
 * [Exact Tuning]
 * basefreq=8.1757989156437073336
 * note 0=<float cents, toFixed(5)>
 * ...
 * note 127=<float cents, toFixed(5)>
 * ```
 *
 * The default basefreq is 8.1757989156437073336 Hz, which equals MIDI note 0
 * when A4 = 440 Hz (i.e. 440 × 2^(−69/12)).  With this basefreq, 12-TET gives
 * note k = k×100 cents exactly.
 *
 * Convenience usage with an existing TuningSystem:
 *   `writeTun(tuningToMtsFrequencies(t), 'My Scale')`
 */

import { freqToCents } from '../core/cents.js';
import { type Chord, realizeChordFreqs } from '../core/chord.js';
import { freqToMidiFloat, midiToFreq, A4_HZ_DEFAULT } from '../core/midi.js';

/** Default base frequency: MIDI note 0 at A4 = 440 Hz (440 × 2^(−69/12)). */
export const TUN_DEFAULT_BASEFREQ_HZ = 440 * 2 ** (-69 / 12);

/** Options for {@link writeTun}. */
export interface TunOptions {
  /** Base frequency in Hz. Default {@link TUN_DEFAULT_BASEFREQ_HZ}. */
  readonly basefreqHz?: number;
}

/**
 * Write 128 frequencies as an AnaMark .tun file.
 *
 * @param frequenciesHz - Frequencies for MIDI keys 0..127 (must have length 128,
 *   all finite and > 0).
 * @param name - Human-readable tuning name; control characters and newlines are
 *   replaced with spaces to keep the comment line well-formed.
 * @param opts - Optional base frequency override.
 * @throws {RangeError} if frequenciesHz.length !== 128, any frequency is not
 *   finite or ≤ 0, or basefreqHz is not finite or ≤ 0.
 */
export function writeTun(
  frequenciesHz: readonly number[],
  name: string,
  opts?: TunOptions,
): string {
  if (frequenciesHz.length !== 128) {
    throw new RangeError(
      `writeTun: frequenciesHz must have length 128, got ${frequenciesHz.length}`,
    );
  }

  const basefreqHz = opts?.basefreqHz ?? TUN_DEFAULT_BASEFREQ_HZ;

  if (!Number.isFinite(basefreqHz) || basefreqHz <= 0) {
    throw new RangeError(`writeTun: basefreqHz must be finite and > 0, got ${basefreqHz}`);
  }

  // Validate all frequencies up front (fail fast).
  for (let i = 0; i < 128; i++) {
    const hz = frequenciesHz[i] as number;
    if (!Number.isFinite(hz) || hz <= 0) {
      throw new RangeError(`writeTun: frequenciesHz[${i}] must be finite and > 0, got ${hz}`);
    }
  }

  // Strip control characters (including newlines) from the name.
  // eslint-disable-next-line no-control-regex
  const safeName = name.replace(/[\x00-\x1f\x7f]/g, ' ');

  const lines: string[] = [];

  // Comment header.
  lines.push(`; ${safeName}`);
  lines.push('; Generated by ruri');

  // [Tuning] section — integer cents.
  lines.push('[Tuning]');
  for (let k = 0; k < 128; k++) {
    const hz = frequenciesHz[k] as number;
    const c = freqToCents(hz, basefreqHz);
    lines.push(`note ${k}=${Math.round(c)}`);
  }

  // [Exact Tuning] section — 5-decimal-place cents.
  lines.push('[Exact Tuning]');
  // Emit the ACTUAL basefreq used for the cent computations (not the default),
  // so the file is internally consistent and a conforming parser recovers the
  // same pitches. Using the default here for a custom basefreq would shift every
  // note by log2(basefreqHz / default) octaves.
  lines.push(`basefreq=${basefreqHz.toPrecision(20)}`);
  for (let k = 0; k < 128; k++) {
    const hz = frequenciesHz[k] as number;
    const c = freqToCents(hz, basefreqHz);
    lines.push(`note ${k}=${c.toFixed(5)}`);
  }

  return lines.join('\n') + '\n';
}

/** Options for {@link chordToTun}. */
export interface ChordToTunOptions extends TunOptions {
  /**
   * A4 reference frequency in Hz used to fill non-chord MIDI keys with standard 12-TET.
   * Default: 440.
   */
  readonly a4Hz?: number;
}

/**
 * Export a microtonal `Chord` directly as an AnaMark `.tun` string.
 *
 * Socratic Q114: `chordToMts(chord, rootHz)` maps a chord's exact frequencies onto
 * the nearest MIDI keys and returns a ready-to-send SysEx byte-stream — but there is
 * no `.tun` equivalent. Going from a `Chord` to a `.tun` file still requires three
 * manual steps: `realizeChordFreqs → fill 128-key array → writeTun`.
 * If `Chord` is truly first-class (with `chordToMts`, `chordToScl`, `chordToSmf`…),
 * exporting it as `.tun` should also be one call.
 *
 * Algorithm (mirrors `chordToMts`):
 * 1. Realize chord frequencies: `realizeChordFreqs(chord, rootHz)`.
 * 2. Fill a 128-entry array with standard 12-TET frequencies (via `midiToFreq`).
 * 3. For each chord frequency, find the nearest MIDI key (clamped to [0, 127]) and
 *    overwrite that slot with the exact chord Hz.
 * 4. Encode with `writeTun` and return the `.tun` string.
 *
 * Non-chord MIDI keys retain standard 12-TET so that an unrelated synth part is not
 * detuned.
 *
 * @param chord   - The chord to export.
 * @param rootHz  - Absolute frequency of the chord root in Hz.
 * @param name    - Human-readable name for the `.tun` file comment header.
 *                  Defaults to `chord.name` (or `'chord'` if that is empty).
 * @param opts    - Optional A4 reference Hz and basefreq override.
 *
 * @throws {RangeError} if `chord` has no intervals.
 * @throws {RangeError} if `rootHz` is not finite or ≤ 0.
 *
 * @example
 * const justMajor = chordFromRatios('just-major', [[1,1],[5,4],[3,2]]);
 * const tun = chordToTun(justMajor, 261.63);
 * fs.writeFileSync('just-major.tun', tun, 'utf8');
 */
export function chordToTun(
  chord: Chord,
  rootHz: number,
  name?: string,
  opts?: ChordToTunOptions,
): string {
  if (chord.intervals.length === 0) {
    throw new RangeError('chordToTun: chord must have at least one interval');
  }
  if (!Number.isFinite(rootHz) || rootHz <= 0) {
    throw new RangeError(`chordToTun: rootHz must be finite and > 0, got ${rootHz}`);
  }

  const a4Hz = opts?.a4Hz ?? A4_HZ_DEFAULT;
  const tunName = name ?? (chord.name.length > 0 ? chord.name : 'chord');

  // Start with standard 12-TET for all 128 MIDI keys.
  const frequencies: number[] = Array.from({ length: 128 }, (_, k) => midiToFreq(k, a4Hz));

  // Overwrite the nearest MIDI key for each chord frequency.
  const chordFreqs = realizeChordFreqs(chord, rootHz);
  for (const hz of chordFreqs) {
    const midiFloat = freqToMidiFloat(hz, a4Hz);
    const key = Math.max(0, Math.min(127, Math.round(midiFloat)));
    (frequencies as number[])[key] = hz;
  }

  const { a4Hz: _a4Hz, ...tunOpts } = opts ?? {};
  void _a4Hz;
  return writeTun(frequencies, tunName, Object.keys(tunOpts).length > 0 ? tunOpts : undefined);
}
