/**
 * AnaMark .tun (TUN) tuning file writer.
 *
 * Emits the broadly-compatible v1 layout with both a [Tuning] section (integer
 * cents) and an [Exact Tuning] section (5-decimal-place cents).  All cent values
 * are **absolute cents above basefreq** — i.e. 1200·log₂(f / basefreq).
 *
 * File structure:
 *
 * ```
 * ; <name>
 * ; Generated by ruri
 * [Tuning]
 * note 0=<int cents>
 * ...
 * note 127=<int cents>
 * [Exact Tuning]
 * basefreq=8.1757989156437073336
 * note 0=<float cents, toFixed(5)>
 * ...
 * note 127=<float cents, toFixed(5)>
 * ```
 *
 * The default basefreq is 8.1757989156437073336 Hz, which equals MIDI note 0
 * when A4 = 440 Hz (i.e. 440 × 2^(−69/12)).  With this basefreq, 12-TET gives
 * note k = k×100 cents exactly.
 *
 * Convenience usage with an existing TuningSystem:
 *   `writeTun(tuningToMtsFrequencies(t), 'My Scale')`
 */

import { freqToCents } from '../core/cents.js';

/** Default base frequency: MIDI note 0 at A4 = 440 Hz (440 × 2^(−69/12)). */
export const TUN_DEFAULT_BASEFREQ_HZ = 440 * 2 ** (-69 / 12);

/** Options for {@link writeTun}. */
export interface TunOptions {
  /** Base frequency in Hz. Default {@link TUN_DEFAULT_BASEFREQ_HZ}. */
  readonly basefreqHz?: number;
}

/**
 * Write 128 frequencies as an AnaMark .tun file.
 *
 * @param frequenciesHz - Frequencies for MIDI keys 0..127 (must have length 128,
 *   all finite and > 0).
 * @param name - Human-readable tuning name; control characters and newlines are
 *   replaced with spaces to keep the comment line well-formed.
 * @param opts - Optional base frequency override.
 * @throws {RangeError} if frequenciesHz.length !== 128, any frequency is not
 *   finite or ≤ 0, or basefreqHz is not finite or ≤ 0.
 */
export function writeTun(
  frequenciesHz: readonly number[],
  name: string,
  opts?: TunOptions,
): string {
  if (frequenciesHz.length !== 128) {
    throw new RangeError(
      `writeTun: frequenciesHz must have length 128, got ${frequenciesHz.length}`,
    );
  }

  const basefreqHz = opts?.basefreqHz ?? TUN_DEFAULT_BASEFREQ_HZ;

  if (!Number.isFinite(basefreqHz) || basefreqHz <= 0) {
    throw new RangeError(`writeTun: basefreqHz must be finite and > 0, got ${basefreqHz}`);
  }

  // Validate all frequencies up front (fail fast).
  for (let i = 0; i < 128; i++) {
    const hz = frequenciesHz[i] as number;
    if (!Number.isFinite(hz) || hz <= 0) {
      throw new RangeError(`writeTun: frequenciesHz[${i}] must be finite and > 0, got ${hz}`);
    }
  }

  // Strip control characters (including newlines) from the name.
  // eslint-disable-next-line no-control-regex
  const safeName = name.replace(/[\x00-\x1f\x7f]/g, ' ');

  const lines: string[] = [];

  // Comment header.
  lines.push(`; ${safeName}`);
  lines.push('; Generated by ruri');

  // [Tuning] section — integer cents.
  lines.push('[Tuning]');
  for (let k = 0; k < 128; k++) {
    const hz = frequenciesHz[k] as number;
    const c = freqToCents(hz, basefreqHz);
    lines.push(`note ${k}=${Math.round(c)}`);
  }

  // [Exact Tuning] section — 5-decimal-place cents.
  lines.push('[Exact Tuning]');
  // Emit basefreq with full stored precision so parsers can verify the reference.
  lines.push(`basefreq=${TUN_DEFAULT_BASEFREQ_HZ.toPrecision(20)}`);
  for (let k = 0; k < 128; k++) {
    const hz = frequenciesHz[k] as number;
    const c = freqToCents(hz, basefreqHz);
    lines.push(`note ${k}=${c.toFixed(5)}`);
  }

  return lines.join('\n') + '\n';
}
